version: '3.9'

volumes:
    logs:
        driver: local

services:
    php:
        build: ./docker
        #image: diveinteractive/php81-alpine
        container_name: PHP8.3
        working_dir: /var/www/public
        #working_dir: /var/www <- octane
        command: php -S 0.0.0.0:8080 -t ./
        #command: [ "php", "artisan", "octane:start", "--host=0.0.0.0", "--port=8000"] <-- octane
        environment:
            docker: "true"
        ports:
            #- 8000:8000 <-- octane
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        networks:
            - app-network
                    
    mariadb:
        container_name: DBMaria
        image: mariadb
        ports:
            - 4306:3306
        restart: always
        environment:
            MYSQL_DATABASE: kusikuydb
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        volumes:
            - ./docker/data:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge